
server {
    # 서버가 요청을 들을 포트
    listen 808;
    server_name localhost;


    root /usr/share/nginx/html;
    location / {
        index index.html;
    }

    location ~\.(gif|jpg|png)$ {
        root /data/images;
    }
}